### ISSUE TITLE
Crash android.os.DeadSystemException on Galaxy A34,Galaxy A21s,Vivo 1935,Transsion Note 8; Android 9, Android 10, Android 14

### ISSUE THREAD

**Issue by byh000** [trustdecision/trustdevice-android#29]
# Crashlytics - Stack trace
# Application: com.blvision.hita
# Platform: android
# Version: 0.0.6 (16)
# Issue: 6eb28270d88c441610a5428026ba0496
# Session: 65F07C8302F1000175A1077B029E989C_DNE_0_v2
# Date: Tue Mar 12 2024 23:02:21 GMT+0700 (Western Indonesia Time)

Fatal Exception: android.os.DeadSystemRuntimeException: android.os.DeadSystemException
       at android.app.ApplicationPackageManager.getInstalledPackagesAsUser(ApplicationPackageManager.java:1274)
       at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:1251)
       at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:1245)
       at c.b.<init>(AppListCollector.kt:7)
       at b.a.m(FMCore.kt:1)
       at b.a.b(FMCore.kt:17)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Caused by android.os.DeadSystemException:
       at android.app.ApplicationPackageManager.getInstalledPackagesAsUser(ApplicationPackageManager.java:1274)
       at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:1251)
       at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:1245)
       at c.b.<init>(AppListCollector.kt:7)
       at b.a.m(FMCore.kt:1)
       at b.a.b(FMCore.kt:17)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

pool-13-thread-1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
       at java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3466)
       at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3437)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1176)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:905)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1071)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by lurenman** [comment]
The getInstalledPackages API has been safely called

**Comment by byh000** [comment]
> The getInstalledPackages API has been safely called
I use sdk version is 1.0.5.  Are you sure method has ben safely called? Whether there are other reasons for this problem

**Comment by lurenman** [comment]
I just fixed this bug and the next version will take effect

**Comment by byh000** [comment]
> I just fixed this bug and the next version will take effect

Thanks! Can you tell me next version release time?

**Comment by lurenman** [comment]
It has been updated, corresponding to version 1.0.6

**Comment by byh000** [comment]
> It has been updated, corresponding to version 1.0.6

Ok, Thank you
